### PR TITLE
chore - Spelling and grammar

### PR DESCRIPTION
**Pull request by jwhett**
Errors noticed while following the egg timer tutorial.

---

Thank you for writing this tutorial. I'll have to read it a couple more times for it to fully sink in, but it's a great start for the Gio journey.

### CODE REVIEW

**Comment by jonegil** [comment]
Thank you so much, highly appreciated. 

Which parts do you find most challenging. I used the tutorial to write myself into Gio, so I'm equally interested in hearing where you got stuck.

**Comment by jwhett** [comment]
You're welcome @jonegil :smile: 

I think about ch8 things started to get more difficult. I'm planning on going through it at least one more time. We have a newborn so my brain has limited capacity at any given moment :laughing: As things continued to nest more and more in the anonymous function, it became more difficult to keep things straight in my head.

@whereswaldon pointed me to your tutorial and I think it's great. I think I'll be able to better form some more constructive thoughts on my second read through.

**Comment by jonegil** [comment]
Congratulations so much with you newborn. That is indeed an intense period. 

What I spent most time on when learning this part of Gio was getting used to the wording. We don't draw lines and areas outright. Instead we define some shape or form, then fill that form with color. 

Defining is done by *clip*, maybe a better word could be *shape*, at least that helps me think about it. 


Are you able to run the code and see how it changes if you make adjustments?

**Comment by jwhett** [comment]
Thanks @jonegil! 

Maybe I'll find some time this Sunday... If not, I've promised to myself that I would run through it again so I'll surely have some more thoughts after that.

**Pull request merged**
