### PR TITLE
eggtimer: fix typos in all chapters

### PR DESCRIPTION
**Pull request by craftyguy**

### CODE REVIEW

**Review by jonegil — APPROVED** [review]
You are a writers best friend. I am truly grateful (and a little embarrassed). 

Anything else you would like to point out? Structure, clarity, depth, how did it communicate to you?

**Comment by craftyguy** [comment]
@jonegil no worries, I'm happy to help!

I quite liked it! I just started using Gio a few days ago, and your eggtimer tutorial was very helpful for me to understand the basics. I'm really looking forward to the teleprompter tutorial :)

**Comment by jonegil** [comment]
Thanks. Glad to hear it. 

I have another project up the sleeves, after the prompter, making a skeleton app or starter kit for a more realistic desktop app. That one I hope can serve as a building block for real world products.

**Comment by craftyguy** [comment]
Interesting, I'm curious which approach you'll take with that. I recently "discovered" the "router"/"view manager" approach in the gio-examples/components/pages package, but I have no idea if that's a good basis for real world apps or not since I'm so unfamiliar with Gio at this point.


Anyways, keep up the excellent work :D

**Pull request merged**
